"""is_generic should be string

Revision ID: 13f342128f75
Revises: b86c5d893df9
Create Date: 2017-05-18 12:13:10.381728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f342128f75'
down_revision = 'b86c5d893df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
