"""fix ref to parent should be product

Revision ID: 14d2bff6330a
Revises: 637d53e70a06
Create Date: 2017-05-18 12:58:18.460465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d2bff6330a'
down_revision = '637d53e70a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
