"""fix ref to parent should be product

Revision ID: 302c225479da
Revises: 14d2bff6330a
Create Date: 2017-05-18 12:59:16.474088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302c225479da'
down_revision = '14d2bff6330a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
