"""add applicant name and licence no

Revision ID: 406a2a8bd71a
Revises: 8b6745302642
Create Date: 2017-05-23 15:00:26.592404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406a2a8bd71a'
down_revision = '8b6745302642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('applicant_licence_no', sa.String(), nullable=False))
    op.add_column('product', sa.Column('applicant_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'applicant_name')
    op.drop_column('product', 'applicant_licence_no')
    # ### end Alembic commands ###
