"""nappi code not unique without num_packs

Revision ID: 50290ac83d91
Revises: 820fb4aae951
Create Date: 2017-05-18 16:06:14.289402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50290ac83d91'
down_revision = '820fb4aae951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'is_generic'])
    op.drop_constraint(u'product_unique_nappi_code_pack_size_is_generic', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'product_unique_nappi_code_pack_size_is_generic', 'product', ['nappi_code', 'pack_size', 'is_generic'])
    op.drop_constraint('product_unique', 'product', type_='unique')
    # ### end Alembic commands ###
