"""really change is_generic to string

Revision ID: 637d53e70a06
Revises: f96381c05a8e
Create Date: 2017-05-18 12:48:33.587427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637d53e70a06'
down_revision = 'f96381c05a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_generic',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_generic',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
