"""nappi code not unique without regno - just to make mistakes more explicit

Revision ID: 6b5d44286e3e
Revises: c8bbccb94624
Create Date: 2017-05-18 16:27:19.706075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5d44286e3e'
down_revision = 'c8bbccb94624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'product_unique', 'product', type_='unique')
    op.create_unique_constraint('product_unique', 'product', ['regno', 'nappi_code', 'pack_size', 'num_packs', 'schedule', 'is_generic', 'dosage_form'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_unique', 'product', type_='unique')
    op.create_unique_constraint(u'product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'schedule', 'is_generic', 'dosage_form'])
    # ### end Alembic commands ###
