"""nappi code not unique without is_generic

Revision ID: 820fb4aae951
Revises: d481f3099ecf
Create Date: 2017-05-18 15:55:07.852528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820fb4aae951'
down_revision = 'd481f3099ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_unique_nappi_code_pack_size_is_generic', 'product', ['nappi_code', 'pack_size', 'is_generic'])
    op.drop_constraint(u'product_unique_nappi_code_pack_size', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'product_unique_nappi_code_pack_size', 'product', ['nappi_code', 'pack_size'])
    op.drop_constraint('product_unique_nappi_code_pack_size_is_generic', 'product', type_='unique')
    # ### end Alembic commands ###
