"""add equivalence_key field to product

Revision ID: 8b6745302642
Revises: 6b5d44286e3e
Create Date: 2017-05-22 21:39:25.489558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6745302642'
down_revision = '6b5d44286e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('equivalence_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'equivalence_key')
    # ### end Alembic commands ###
