"""remove mistaken primary key for product_ingredient relationship


Revision ID: 97bf34154651
Revises: dd2344bd4959
Create Date: 2017-05-18 15:24:41.409397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bf34154651'
down_revision = 'dd2344bd4959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("product_ingredient_pkey", "product_ingredient", ["id", ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
