"""fix not null constraints

Revision ID: b86c5d893df9
Revises: a07768b0d4c0
Create Date: 2017-05-18 11:44:01.238577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b86c5d893df9'
down_revision = 'a07768b0d4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ingredient', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('ingredient_unique_name_unit', 'ingredient', ['name', 'unit'])
    op.drop_constraint(u'_unique_name_unit', 'ingredient', type_='unique')
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'nappi_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'pack_size',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('product', 'regno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_ingredient', 'strength',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('product_ingredient_unique_product_ingredient_strength', 'product_ingredient', ['product_id', 'ingredient_id', 'strength'])
    op.drop_constraint(u'_unique_product_ingredient_strength', 'product_ingredient', type_='unique')
    op.alter_column('product_sep', 'sep',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_sep', 'sep',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint(u'_unique_product_ingredient_strength', 'product_ingredient', ['product_id', 'ingredient_id', 'strength'])
    op.drop_constraint('product_ingredient_unique_product_ingredient_strength', 'product_ingredient', type_='unique')
    op.alter_column('product_ingredient', 'strength',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'regno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'pack_size',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product', 'nappi_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(u'_unique_name_unit', 'ingredient', ['name', 'unit'])
    op.drop_constraint('ingredient_unique_name_unit', 'ingredient', type_='unique')
    op.alter_column('ingredient', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ingredient', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
