"""nappi code not unique without dosage_form

Revision ID: c8bbccb94624
Revises: cd9743607a93
Create Date: 2017-05-18 16:15:20.733645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8bbccb94624'
down_revision = 'cd9743607a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'product_unique', 'product', type_='unique')
    op.create_unique_constraint('product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'schedule', 'is_generic', 'dosage_form'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_unique', 'product', type_='unique')
    op.create_unique_constraint(u'product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'schedule', 'is_generic'])
    # ### end Alembic commands ###
