"""nappi code not unique without schedule

Revision ID: cd9743607a93
Revises: 50290ac83d91
Create Date: 2017-05-18 16:09:49.638941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9743607a93'
down_revision = '50290ac83d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'product_unique', 'product', type_='unique')
    op.create_unique_constraint('product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'schedule', 'is_generic'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_unique', 'product', type_='unique')
    op.create_unique_constraint(u'product_unique', 'product', ['nappi_code', 'pack_size', 'num_packs', 'is_generic'])
    # ### end Alembic commands ###
