"""nappi code not unique without pack size

Revision ID: d481f3099ecf
Revises: 97bf34154651
Create Date: 2017-05-18 15:32:43.344970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd481f3099ecf'
down_revision = '97bf34154651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_unique_nappi_code_pack_size', 'product', ['nappi_code', 'pack_size'])
    op.drop_constraint(u'product_nappi_code_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'product_nappi_code_key', 'product', ['nappi_code'])
    op.drop_constraint('product_unique_nappi_code_pack_size', 'product', type_='unique')
    # ### end Alembic commands ###
