"""remove mistaken primary key for product_ingredient relationship


Revision ID: dd2344bd4959
Revises: 302c225479da
Create Date: 2017-05-18 15:18:43.007292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2344bd4959'
down_revision = '302c225479da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ingredient_pkey', 'product_ingredient', type_='primary')
    op.add_column('product_ingredient', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.alter_column('product_ingredient', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_ingredient', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_ingredient', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_ingredient', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_ingredient', 'id')
    # ### end Alembic commands ###
