"""add product.num_packs

Revision ID: f96381c05a8e
Revises: 13f342128f75
Create Date: 2017-05-18 12:35:51.865154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96381c05a8e'
down_revision = '13f342128f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('num_packs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'num_packs')
    # ### end Alembic commands ###
